services:
  db:
    image: zmallwood/db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  game_server:
    image: zmallwood/game_server
    ports:
      - 8765:8765
    expose:
      - 8765
    links:
      - "db"
    depends_on:
      - db

  http_server:
    image: zmallwood/http_server
    ports:
      - 80:80
    expose:
      - 80
    links:
      - "game_server"
    depends_on:
      - game_server
volumes:
  pgdata:
