services:
  neovim:
    build: .
    privileged: true
    ports:
      - "8000:8000"
      - "8765:8765"
    expose:
      - "8000"
      - "8765"
    devices:
        - /dev/fuse
    volumes:
      - /lib/modules:/lib/modules # Only required for FUSE - see above
      - /sbin/modprobe:/sbin/modprobe
      - /home/andreas/code:/app/code
    stdin_open: true # docker run -i
    tty: true        # docker run -t
