FROM nginx:stable-alpine
RUN apk add --update python3
COPY JourneyOfDreams.html /usr/share/nginx/html/JourneyOfDreams.html
COPY JourneyOfDreams.js /usr/share/nginx/html/JourneyOfDreams.js
COPY JourneyOfDreams.wasm /usr/share/nginx/html/JourneyOfDreams.wasm